// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.5.0
// source: read.proto

package reader

import (
	test "../../protocol/test"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	write "protocol/write"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReadV1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User *write.StUser `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Dax  *test.Test    `protobuf:"bytes,2,opt,name=dax,proto3" json:"dax,omitempty"`
}

func (x *ReadV1) Reset() {
	*x = ReadV1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_read_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadV1) ProtoMessage() {}

func (x *ReadV1) ProtoReflect() protoreflect.Message {
	mi := &file_read_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadV1.ProtoReflect.Descriptor instead.
func (*ReadV1) Descriptor() ([]byte, []int) {
	return file_read_proto_rawDescGZIP(), []int{0}
}

func (x *ReadV1) GetUser() *write.StUser {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *ReadV1) GetDax() *test.Test {
	if x != nil {
		return x.Dax
	}
	return nil
}

var File_read_proto protoreflect.FileDescriptor

var file_read_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x72, 0x65, 0x61, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x72, 0x70,
	0x63, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x62, 0x61, 0x73, 0x65, 0x1a, 0x0c, 0x77, 0x72,
	0x69, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1c, 0x6e, 0x69, 0x6f, 0x2f,
	0x74, 0x69, 0x67, 0x65, 0x72, 0x77, 0x61, 0x6e, 0x67, 0x2f, 0x6e, 0x69, 0x6f, 0x2e, 0x74, 0x65,
	0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x5a, 0x0a, 0x06, 0x52, 0x65, 0x61, 0x64,
	0x56, 0x31, 0x12, 0x2a, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x16, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x62, 0x61, 0x73,
	0x65, 0x2e, 0x53, 0x74, 0x55, 0x73, 0x65, 0x72, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x24,
	0x0a, 0x03, 0x64, 0x61, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6f, 0x72,
	0x67, 0x2e, 0x6e, 0x69, 0x6f, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x54, 0x65, 0x73, 0x74, 0x52,
	0x03, 0x64, 0x61, 0x78, 0x42, 0x29, 0x0a, 0x0f, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63,
	0x6f, 0x6c, 0x2f, 0x72, 0x65, 0x61, 0x64, 0x5a, 0x16, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x6f, 0x6c, 0x2f, 0x72, 0x65, 0x61, 0x64, 0x3b, 0x72, 0x65, 0x61, 0x64, 0x65, 0x72, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_read_proto_rawDescOnce sync.Once
	file_read_proto_rawDescData = file_read_proto_rawDesc
)

func file_read_proto_rawDescGZIP() []byte {
	file_read_proto_rawDescOnce.Do(func() {
		file_read_proto_rawDescData = protoimpl.X.CompressGZIP(file_read_proto_rawDescData)
	})
	return file_read_proto_rawDescData
}

var file_read_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_read_proto_goTypes = []interface{}{
	(*ReadV1)(nil),       // 0: rpc.cloud.base.ReadV1
	(*write.StUser)(nil), // 1: rpc.cloud.base.StUser
	(*test.Test)(nil),    // 2: org.nio.test.Test
}
var file_read_proto_depIdxs = []int32{
	1, // 0: rpc.cloud.base.ReadV1.user:type_name -> rpc.cloud.base.StUser
	2, // 1: rpc.cloud.base.ReadV1.dax:type_name -> org.nio.test.Test
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_read_proto_init() }
func file_read_proto_init() {
	if File_read_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_read_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadV1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_read_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_read_proto_goTypes,
		DependencyIndexes: file_read_proto_depIdxs,
		MessageInfos:      file_read_proto_msgTypes,
	}.Build()
	File_read_proto = out.File
	file_read_proto_rawDesc = nil
	file_read_proto_goTypes = nil
	file_read_proto_depIdxs = nil
}
