// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: read.proto

package ./protocol/read;

public final class Read {
  private Read() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ReadV1OrBuilder extends
      // @@protoc_insertion_point(interface_extends:rpc.cloud.base.ReadV1)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.rpc.cloud.base.StUser user = 1;</code>
     */
    boolean hasUser();
    /**
     * <code>.rpc.cloud.base.StUser user = 1;</code>
     */
    ./protocol/write.Writer.StUser getUser();
    /**
     * <code>.rpc.cloud.base.StUser user = 1;</code>
     */
    ./protocol/write.Writer.StUserOrBuilder getUserOrBuilder();

    /**
     * <code>.org.nio.test.Test dax = 2;</code>
     */
    boolean hasDax();
    /**
     * <code>.org.nio.test.Test dax = 2;</code>
     */
    ./protocol/test.TestOuterClass.Test getDax();
    /**
     * <code>.org.nio.test.Test dax = 2;</code>
     */
    ./protocol/test.TestOuterClass.TestOrBuilder getDaxOrBuilder();
  }
  /**
   * Protobuf type {@code rpc.cloud.base.ReadV1}
   */
  public  static final class ReadV1 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:rpc.cloud.base.ReadV1)
      ReadV1OrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ReadV1.newBuilder() to construct.
    private ReadV1(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ReadV1() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ReadV1(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              ./protocol/write.Writer.StUser.Builder subBuilder = null;
              if (user_ != null) {
                subBuilder = user_.toBuilder();
              }
              user_ = input.readMessage(./protocol/write.Writer.StUser.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(user_);
                user_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              ./protocol/test.TestOuterClass.Test.Builder subBuilder = null;
              if (dax_ != null) {
                subBuilder = dax_.toBuilder();
              }
              dax_ = input.readMessage(./protocol/test.TestOuterClass.Test.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(dax_);
                dax_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ./protocol/read.Read.internal_static_rpc_cloud_base_ReadV1_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ./protocol/read.Read.internal_static_rpc_cloud_base_ReadV1_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ./protocol/read.Read.ReadV1.class, ./protocol/read.Read.ReadV1.Builder.class);
    }

    public static final int USER_FIELD_NUMBER = 1;
    private ./protocol/write.Writer.StUser user_;
    /**
     * <code>.rpc.cloud.base.StUser user = 1;</code>
     */
    public boolean hasUser() {
      return user_ != null;
    }
    /**
     * <code>.rpc.cloud.base.StUser user = 1;</code>
     */
    public ./protocol/write.Writer.StUser getUser() {
      return user_ == null ? ./protocol/write.Writer.StUser.getDefaultInstance() : user_;
    }
    /**
     * <code>.rpc.cloud.base.StUser user = 1;</code>
     */
    public ./protocol/write.Writer.StUserOrBuilder getUserOrBuilder() {
      return getUser();
    }

    public static final int DAX_FIELD_NUMBER = 2;
    private ./protocol/test.TestOuterClass.Test dax_;
    /**
     * <code>.org.nio.test.Test dax = 2;</code>
     */
    public boolean hasDax() {
      return dax_ != null;
    }
    /**
     * <code>.org.nio.test.Test dax = 2;</code>
     */
    public ./protocol/test.TestOuterClass.Test getDax() {
      return dax_ == null ? ./protocol/test.TestOuterClass.Test.getDefaultInstance() : dax_;
    }
    /**
     * <code>.org.nio.test.Test dax = 2;</code>
     */
    public ./protocol/test.TestOuterClass.TestOrBuilder getDaxOrBuilder() {
      return getDax();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (user_ != null) {
        output.writeMessage(1, getUser());
      }
      if (dax_ != null) {
        output.writeMessage(2, getDax());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (user_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getUser());
      }
      if (dax_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getDax());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ./protocol/read.Read.ReadV1)) {
        return super.equals(obj);
      }
      ./protocol/read.Read.ReadV1 other = (./protocol/read.Read.ReadV1) obj;

      boolean result = true;
      result = result && (hasUser() == other.hasUser());
      if (hasUser()) {
        result = result && getUser()
            .equals(other.getUser());
      }
      result = result && (hasDax() == other.hasDax());
      if (hasDax()) {
        result = result && getDax()
            .equals(other.getDax());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasUser()) {
        hash = (37 * hash) + USER_FIELD_NUMBER;
        hash = (53 * hash) + getUser().hashCode();
      }
      if (hasDax()) {
        hash = (37 * hash) + DAX_FIELD_NUMBER;
        hash = (53 * hash) + getDax().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ./protocol/read.Read.ReadV1 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ./protocol/read.Read.ReadV1 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ./protocol/read.Read.ReadV1 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ./protocol/read.Read.ReadV1 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ./protocol/read.Read.ReadV1 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ./protocol/read.Read.ReadV1 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ./protocol/read.Read.ReadV1 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ./protocol/read.Read.ReadV1 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ./protocol/read.Read.ReadV1 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ./protocol/read.Read.ReadV1 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ./protocol/read.Read.ReadV1 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ./protocol/read.Read.ReadV1 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(./protocol/read.Read.ReadV1 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code rpc.cloud.base.ReadV1}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:rpc.cloud.base.ReadV1)
        ./protocol/read.Read.ReadV1OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ./protocol/read.Read.internal_static_rpc_cloud_base_ReadV1_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ./protocol/read.Read.internal_static_rpc_cloud_base_ReadV1_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ./protocol/read.Read.ReadV1.class, ./protocol/read.Read.ReadV1.Builder.class);
      }

      // Construct using ./protocol/read.Read.ReadV1.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (userBuilder_ == null) {
          user_ = null;
        } else {
          user_ = null;
          userBuilder_ = null;
        }
        if (daxBuilder_ == null) {
          dax_ = null;
        } else {
          dax_ = null;
          daxBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ./protocol/read.Read.internal_static_rpc_cloud_base_ReadV1_descriptor;
      }

      public ./protocol/read.Read.ReadV1 getDefaultInstanceForType() {
        return ./protocol/read.Read.ReadV1.getDefaultInstance();
      }

      public ./protocol/read.Read.ReadV1 build() {
        ./protocol/read.Read.ReadV1 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ./protocol/read.Read.ReadV1 buildPartial() {
        ./protocol/read.Read.ReadV1 result = new ./protocol/read.Read.ReadV1(this);
        if (userBuilder_ == null) {
          result.user_ = user_;
        } else {
          result.user_ = userBuilder_.build();
        }
        if (daxBuilder_ == null) {
          result.dax_ = dax_;
        } else {
          result.dax_ = daxBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ./protocol/read.Read.ReadV1) {
          return mergeFrom((./protocol/read.Read.ReadV1)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(./protocol/read.Read.ReadV1 other) {
        if (other == ./protocol/read.Read.ReadV1.getDefaultInstance()) return this;
        if (other.hasUser()) {
          mergeUser(other.getUser());
        }
        if (other.hasDax()) {
          mergeDax(other.getDax());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ./protocol/read.Read.ReadV1 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (./protocol/read.Read.ReadV1) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private ./protocol/write.Writer.StUser user_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          ./protocol/write.Writer.StUser, ./protocol/write.Writer.StUser.Builder, ./protocol/write.Writer.StUserOrBuilder> userBuilder_;
      /**
       * <code>.rpc.cloud.base.StUser user = 1;</code>
       */
      public boolean hasUser() {
        return userBuilder_ != null || user_ != null;
      }
      /**
       * <code>.rpc.cloud.base.StUser user = 1;</code>
       */
      public ./protocol/write.Writer.StUser getUser() {
        if (userBuilder_ == null) {
          return user_ == null ? ./protocol/write.Writer.StUser.getDefaultInstance() : user_;
        } else {
          return userBuilder_.getMessage();
        }
      }
      /**
       * <code>.rpc.cloud.base.StUser user = 1;</code>
       */
      public Builder setUser(./protocol/write.Writer.StUser value) {
        if (userBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          user_ = value;
          onChanged();
        } else {
          userBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.rpc.cloud.base.StUser user = 1;</code>
       */
      public Builder setUser(
          ./protocol/write.Writer.StUser.Builder builderForValue) {
        if (userBuilder_ == null) {
          user_ = builderForValue.build();
          onChanged();
        } else {
          userBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.rpc.cloud.base.StUser user = 1;</code>
       */
      public Builder mergeUser(./protocol/write.Writer.StUser value) {
        if (userBuilder_ == null) {
          if (user_ != null) {
            user_ =
              ./protocol/write.Writer.StUser.newBuilder(user_).mergeFrom(value).buildPartial();
          } else {
            user_ = value;
          }
          onChanged();
        } else {
          userBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.rpc.cloud.base.StUser user = 1;</code>
       */
      public Builder clearUser() {
        if (userBuilder_ == null) {
          user_ = null;
          onChanged();
        } else {
          user_ = null;
          userBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.rpc.cloud.base.StUser user = 1;</code>
       */
      public ./protocol/write.Writer.StUser.Builder getUserBuilder() {
        
        onChanged();
        return getUserFieldBuilder().getBuilder();
      }
      /**
       * <code>.rpc.cloud.base.StUser user = 1;</code>
       */
      public ./protocol/write.Writer.StUserOrBuilder getUserOrBuilder() {
        if (userBuilder_ != null) {
          return userBuilder_.getMessageOrBuilder();
        } else {
          return user_ == null ?
              ./protocol/write.Writer.StUser.getDefaultInstance() : user_;
        }
      }
      /**
       * <code>.rpc.cloud.base.StUser user = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          ./protocol/write.Writer.StUser, ./protocol/write.Writer.StUser.Builder, ./protocol/write.Writer.StUserOrBuilder> 
          getUserFieldBuilder() {
        if (userBuilder_ == null) {
          userBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              ./protocol/write.Writer.StUser, ./protocol/write.Writer.StUser.Builder, ./protocol/write.Writer.StUserOrBuilder>(
                  getUser(),
                  getParentForChildren(),
                  isClean());
          user_ = null;
        }
        return userBuilder_;
      }

      private ./protocol/test.TestOuterClass.Test dax_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          ./protocol/test.TestOuterClass.Test, ./protocol/test.TestOuterClass.Test.Builder, ./protocol/test.TestOuterClass.TestOrBuilder> daxBuilder_;
      /**
       * <code>.org.nio.test.Test dax = 2;</code>
       */
      public boolean hasDax() {
        return daxBuilder_ != null || dax_ != null;
      }
      /**
       * <code>.org.nio.test.Test dax = 2;</code>
       */
      public ./protocol/test.TestOuterClass.Test getDax() {
        if (daxBuilder_ == null) {
          return dax_ == null ? ./protocol/test.TestOuterClass.Test.getDefaultInstance() : dax_;
        } else {
          return daxBuilder_.getMessage();
        }
      }
      /**
       * <code>.org.nio.test.Test dax = 2;</code>
       */
      public Builder setDax(./protocol/test.TestOuterClass.Test value) {
        if (daxBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          dax_ = value;
          onChanged();
        } else {
          daxBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.org.nio.test.Test dax = 2;</code>
       */
      public Builder setDax(
          ./protocol/test.TestOuterClass.Test.Builder builderForValue) {
        if (daxBuilder_ == null) {
          dax_ = builderForValue.build();
          onChanged();
        } else {
          daxBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.org.nio.test.Test dax = 2;</code>
       */
      public Builder mergeDax(./protocol/test.TestOuterClass.Test value) {
        if (daxBuilder_ == null) {
          if (dax_ != null) {
            dax_ =
              ./protocol/test.TestOuterClass.Test.newBuilder(dax_).mergeFrom(value).buildPartial();
          } else {
            dax_ = value;
          }
          onChanged();
        } else {
          daxBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.org.nio.test.Test dax = 2;</code>
       */
      public Builder clearDax() {
        if (daxBuilder_ == null) {
          dax_ = null;
          onChanged();
        } else {
          dax_ = null;
          daxBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.org.nio.test.Test dax = 2;</code>
       */
      public ./protocol/test.TestOuterClass.Test.Builder getDaxBuilder() {
        
        onChanged();
        return getDaxFieldBuilder().getBuilder();
      }
      /**
       * <code>.org.nio.test.Test dax = 2;</code>
       */
      public ./protocol/test.TestOuterClass.TestOrBuilder getDaxOrBuilder() {
        if (daxBuilder_ != null) {
          return daxBuilder_.getMessageOrBuilder();
        } else {
          return dax_ == null ?
              ./protocol/test.TestOuterClass.Test.getDefaultInstance() : dax_;
        }
      }
      /**
       * <code>.org.nio.test.Test dax = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          ./protocol/test.TestOuterClass.Test, ./protocol/test.TestOuterClass.Test.Builder, ./protocol/test.TestOuterClass.TestOrBuilder> 
          getDaxFieldBuilder() {
        if (daxBuilder_ == null) {
          daxBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              ./protocol/test.TestOuterClass.Test, ./protocol/test.TestOuterClass.Test.Builder, ./protocol/test.TestOuterClass.TestOrBuilder>(
                  getDax(),
                  getParentForChildren(),
                  isClean());
          dax_ = null;
        }
        return daxBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:rpc.cloud.base.ReadV1)
    }

    // @@protoc_insertion_point(class_scope:rpc.cloud.base.ReadV1)
    private static final ./protocol/read.Read.ReadV1 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ./protocol/read.Read.ReadV1();
    }

    public static ./protocol/read.Read.ReadV1 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ReadV1>
        PARSER = new com.google.protobuf.AbstractParser<ReadV1>() {
      public ReadV1 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ReadV1(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ReadV1> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ReadV1> getParserForType() {
      return PARSER;
    }

    public ./protocol/read.Read.ReadV1 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_cloud_base_ReadV1_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_cloud_base_ReadV1_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nread.proto\022\016rpc.cloud.base\032\014writer.pro" +
      "to\032\030nio/tigerwang/test.proto\"O\n\006ReadV1\022$" +
      "\n\004user\030\001 \001(\0132\026.rpc.cloud.base.StUser\022\037\n\003" +
      "dax\030\002 \001(\0132\022.org.nio.test.TestB)\n\017./proto" +
      "col/readZ\026./protocol/read;readerb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          ./protocol/write.Writer.getDescriptor(),
          ./protocol/test.TestOuterClass.getDescriptor(),
        }, assigner);
    internal_static_rpc_cloud_base_ReadV1_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_rpc_cloud_base_ReadV1_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_cloud_base_ReadV1_descriptor,
        new java.lang.String[] { "User", "Dax", });
    ./protocol/write.Writer.getDescriptor();
    ./protocol/test.TestOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
